/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models

import com.mazekine.client.models.AddressOwnerModel
import com.mazekine.client.models.AddressWalletModel
import com.mazekine.client.models.TransactionModel

/**
 * 
 * @param address 
 * @param currency 
 * @param wallet 
 * @param owner 
 * @param transaction 
 */
data class AddressModel (
    val address: kotlin.String? = null,
    val currency: kotlin.String? = null,
    val wallet: AddressWalletModel? = null,
    val owner: AddressOwnerModel? = null,
    val transaction: TransactionModel? = null
) {

}

