/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models


/**
 * 
 * @param firstName The first name of address owner.
 * @param lastName The last name of address owner.
 * @param nameVerified The status of name verification: NotVerified, VerifiedByWallet, VerifiedByMazekine.
 * @param ownershipVerified The status of address ownership verification: NotVerified, VerifiedByWallet, VerifiedByMazekine.
 */
data class AddressOwnerModel (
    /* The first name of address owner. */
    val firstName: kotlin.String? = null,
    /* The last name of address owner. */
    val lastName: kotlin.String? = null,
    /* The status of name verification: NotVerified, VerifiedByWallet, VerifiedByMazekine. */
    val nameVerified: kotlin.String? = null,
    /* The status of address ownership verification: NotVerified, VerifiedByWallet, VerifiedByMazekine. */
    val ownershipVerified: kotlin.String? = null
) {

}

