/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models


/**
 * 
 * @param token Auth token.
 * @param rateLimit Rate limit in seconds.
 * @param expiredAt When token will be expired: ISO format.
 */
data class AuthModel (
    /* Auth token. */
    val token: kotlin.String? = null,
    /* Rate limit in seconds. */
    val rateLimit: kotlin.Int? = null,
    /* When token will be expired: ISO format. */
    val expiredAt: kotlin.String? = null
) {

}

