/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models

import com.mazekine.client.models.BalanceAmountModel

/**
 * 
 * @param balance The balances of currencies.
 * @param requests The volume of all available requests.
 */
data class BalanceModel (
    /* The balances of currencies. */
    val balance: kotlin.Array<BalanceAmountModel>? = null,
    /* The volume of all available requests. */
    val requests: kotlin.Int? = null
) {

}

