/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models


/**
 * 
 * @param requestUrl Checking URL.
 * @param address The checking address.
 * @param currency The checking crypto currency.
 */
data class CheckRequestModel (
    /* Checking URL. */
    val requestUrl: kotlin.String? = null,
    /* The checking address. */
    val address: kotlin.String? = null,
    /* The checking crypto currency. */
    val currency: kotlin.String? = null
) {

}

