/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models

import com.mazekine.client.models.TransactionModel

/**
 * 
 * @param id The ID of dispute.
 * @param status The status of dispute: New, InProgress, Confirmed, Rejected, Cancelled.
 * @param transaction The transaction of dispute.
 */
data class DisputeModel (
    /* The ID of dispute. */
    val id: java.util.UUID? = null,
    /* The status of dispute: New, InProgress, Confirmed, Rejected, Cancelled. */
    val status: kotlin.String? = null,
    /* The transaction of dispute. */
    val transaction: TransactionModel? = null
) {

}

