/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models


/**
 * 
 * @param karma The value of karma.
 * @param status The status of karma: ok, limited, blocked.
 */
data class KarmaModel (
    /* The value of karma. */
    val karma: kotlin.Int? = null,
    /* The status of karma: ok, limited, blocked. */
    val status: kotlin.String? = null
) {

}

