/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models

//import com.mazekine.client.models.mapOf

/**
 * 
 * @param type 
 * @param title 
 * @param status 
 * @param detail 
 * @param instance 
 */
data class ProblemDetails (
    val type: kotlin.String? = null,
    val title: kotlin.String? = null,
    val status: kotlin.Int? = null,
    val detail: kotlin.String? = null,
    val instance: kotlin.String? = null
) {

}

