/**
* Mazekine.Api
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.mazekine.client.models

import com.mazekine.client.models.AmountModel
import com.mazekine.client.models.CostModel

/**
 * 
 * @param id 
 * @param date 
 * @param cost 
 * @param balanceAvailable 
 * @param requestsAvailable 
 */
data class TransactionModel (
    val id: java.util.UUID? = null,
    val date: kotlin.String? = null,
    val cost: kotlin.Array<CostModel>? = null,
    val balanceAvailable: kotlin.Array<AmountModel>? = null,
    val requestsAvailable: kotlin.Int? = null
) {

}

